# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BomctlAT030 < Formula
  desc "Format agnostic SBOM tooling"
  homepage "https://github.com/bomctl/bomctl"
  version "0.3.0"
  license "Apache License 2.0"

  on_macos do
    on_intel do
      url "https://github.com/bomctl/bomctl/releases/download/v0.3.0/bomctl_0.3.0_darwin_amd64.tar.gz"
      sha256 "7c7e3fc84f7b1e5771daa4a4afa743736bb86da625dddc017ec61142f58229b0"

      def install
        bin.install "bomctl"
      end
    end
    on_arm do
      url "https://github.com/bomctl/bomctl/releases/download/v0.3.0/bomctl_0.3.0_darwin_arm64.tar.gz"
      sha256 "0685b866d6a7a0175e92a17cbbe0fb344f3ffdd108009317b64dd15c611bb6bc"

      def install
        bin.install "bomctl"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/bomctl/bomctl/releases/download/v0.3.0/bomctl_0.3.0_linux_amd64.tar.gz"
        sha256 "fc27fbbf39ffb68c5e399d14033b1ce6496aa689ae689206e0b6da596fd6c5d5"

        def install
          bin.install "bomctl"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/bomctl/bomctl/releases/download/v0.3.0/bomctl_0.3.0_linux_arm64.tar.gz"
        sha256 "16bf7072c221623222a7c12b433a82d0740ae1ffc8888f30031953123a2022f0"

        def install
          bin.install "bomctl"
        end
      end
    end
  end
end
