# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BomctlAT040 < Formula
  desc "Format agnostic SBOM tooling"
  homepage "https://github.com/bomctl/bomctl"
  version "0.4.0"
  license "Apache License 2.0"

  on_macos do
    on_intel do
      url "https://github.com/bomctl/bomctl/releases/download/v0.4.0/bomctl_0.4.0_darwin_amd64.tar.gz"
      sha256 "6bd56d23f0d1e1bcafc3738efb3b43de182d66df66620efbb438965f8ef6e0f3"

      def install
        bin.install "bomctl"
      end
    end
    on_arm do
      url "https://github.com/bomctl/bomctl/releases/download/v0.4.0/bomctl_0.4.0_darwin_arm64.tar.gz"
      sha256 "07f9ee1d3b24c4fea338846e2ac0b2fbaa5b56d91ef2cd249f4d9c5845ba4791"

      def install
        bin.install "bomctl"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/bomctl/bomctl/releases/download/v0.4.0/bomctl_0.4.0_linux_amd64.tar.gz"
        sha256 "8f5643fae5c08f96a73fad4e6412ed2e8112b006d79927c42cdc5ff86117c709"

        def install
          bin.install "bomctl"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/bomctl/bomctl/releases/download/v0.4.0/bomctl_0.4.0_linux_arm64.tar.gz"
        sha256 "675af2b9cdee43ccd46da740b60e3c5699d45f17d330707c4e622a409bcd9bca"

        def install
          bin.install "bomctl"
        end
      end
    end
  end
end
