# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bomctl < Formula
  desc "Format agnostic SBOM tooling"
  homepage "https://github.com/bomctl/bomctl"
  version "0.2.1"
  license "Apache License 2.0"

  on_macos do
    on_intel do
      url "https://github.com/bomctl/bomctl/releases/download/v0.2.1/bomctl_0.2.1_darwin_amd64.tar.gz"
      sha256 "79496c50b74b15403aed957a2fbc9f411f42d5b2a34f3dc5d472bc953d1dba44"

      def install
        bin.install "bomctl"
      end
    end
    on_arm do
      url "https://github.com/bomctl/bomctl/releases/download/v0.2.1/bomctl_0.2.1_darwin_arm64.tar.gz"
      sha256 "3beb57d44b2f4b5c2df829ccdf56481d5c0585118a5c71331081917497201255"

      def install
        bin.install "bomctl"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/bomctl/bomctl/releases/download/v0.2.1/bomctl_0.2.1_linux_amd64.tar.gz"
        sha256 "26a0a086518188dcc016aaf683665f77dfbe22348d44a30445bd373ebdcdcf9c"

        def install
          bin.install "bomctl"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/bomctl/bomctl/releases/download/v0.2.1/bomctl_0.2.1_linux_arm64.tar.gz"
        sha256 "4040522ff4cb194203d893f61c70cc4541b59654f5f1453878d3c13aad9093ff"

        def install
          bin.install "bomctl"
        end
      end
    end
  end
end
