# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BomctlAT031 < Formula
  desc "Format agnostic SBOM tooling"
  homepage "https://github.com/bomctl/bomctl"
  version "0.3.1"
  license "Apache License 2.0"

  on_macos do
    on_intel do
      url "https://github.com/bomctl/bomctl/releases/download/v0.3.1/bomctl_0.3.1_darwin_amd64.tar.gz"
      sha256 "f36566991655e0896244aa40b5a8f545968017c2f6d03c02e9f3ef40e803b8ef"

      def install
        bin.install "bomctl"
      end
    end
    on_arm do
      url "https://github.com/bomctl/bomctl/releases/download/v0.3.1/bomctl_0.3.1_darwin_arm64.tar.gz"
      sha256 "5628d7adbadb091c36836dce21d271b6a939e420462cf242a8f67d7d34ef46b2"

      def install
        bin.install "bomctl"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/bomctl/bomctl/releases/download/v0.3.1/bomctl_0.3.1_linux_amd64.tar.gz"
        sha256 "f1997e50e7ff78ab50abcd4d17f58e646ca418196252523309dd0a0ce4693fd5"

        def install
          bin.install "bomctl"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/bomctl/bomctl/releases/download/v0.3.1/bomctl_0.3.1_linux_arm64.tar.gz"
        sha256 "b3790e06a8abc424b0884b08e1929a4b745e659dc4a5cd2ccc4cbb8998834267"

        def install
          bin.install "bomctl"
        end
      end
    end
  end
end
