# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bomctl < Formula
  desc "Format agnostic SBOM tooling"
  homepage "https://github.com/bomctl/bomctl"
  version "0.4.1"
  license "Apache License 2.0"

  on_macos do
    on_intel do
      url "https://github.com/bomctl/bomctl/releases/download/v0.4.1/bomctl_0.4.1_darwin_amd64.tar.gz"
      sha256 "ce81628e667af7bb68b7e5bc0505d5eaf3ff81dd010f9e62be7f40f9242874d2"

      def install
        bin.install "bomctl"
      end
    end
    on_arm do
      url "https://github.com/bomctl/bomctl/releases/download/v0.4.1/bomctl_0.4.1_darwin_arm64.tar.gz"
      sha256 "762bb137d583453b849a7b1785ada146ce635c21f0a246dc84b0588eacc114d8"

      def install
        bin.install "bomctl"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/bomctl/bomctl/releases/download/v0.4.1/bomctl_0.4.1_linux_amd64.tar.gz"
        sha256 "0d28f04e15108fcdbfcc46701ad75fd39f6fdab0ba0467da12f8c330f2a72c10"

        def install
          bin.install "bomctl"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/bomctl/bomctl/releases/download/v0.4.1/bomctl_0.4.1_linux_arm64.tar.gz"
        sha256 "6bc25f6154e50f058b5de6c783ee7ad7aabb6f205dd6771a1cfc584f53c0f08a"

        def install
          bin.install "bomctl"
        end
      end
    end
  end
end
