# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bomctl < Formula
  desc "Format agnostic SBOM tooling"
  homepage "https://github.com/bomctl/bomctl"
  version "0.2.0"
  license "Apache License 2.0"

  on_macos do
    on_intel do
      url "https://github.com/bomctl/bomctl/releases/download/v0.2.0/bomctl_0.2.0_darwin_amd64.tar.gz"
      sha256 "5b1805477c1fa7faae2716340b7beeb01e117aa057c4062dd06d8216cd6044de"

      def install
        bin.install "bomctl"
      end
    end
    on_arm do
      url "https://github.com/bomctl/bomctl/releases/download/v0.2.0/bomctl_0.2.0_darwin_arm64.tar.gz"
      sha256 "28e1bf310d9dff38a17a43fb4477986435a1af66de6a9bc1446ef6455045fc19"

      def install
        bin.install "bomctl"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/bomctl/bomctl/releases/download/v0.2.0/bomctl_0.2.0_linux_amd64.tar.gz"
        sha256 "d6f1c7688304057fa21ad9202dd4d2110063b066c2e54fc95850c82b8c655285"

        def install
          bin.install "bomctl"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/bomctl/bomctl/releases/download/v0.2.0/bomctl_0.2.0_linux_arm64.tar.gz"
        sha256 "0a19e7b0ebcb08c7e505b2b57c05e995df9d1f95006e99bdfdeac0351e0ed36c"

        def install
          bin.install "bomctl"
        end
      end
    end
  end
end
