# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BomctlAT042 < Formula
  desc "Format agnostic SBOM tooling"
  homepage "https://github.com/bomctl/bomctl"
  version "0.4.2"
  license "Apache License 2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/bomctl/bomctl/releases/download/v0.4.2/bomctl_0.4.2_darwin_amd64.tar.gz"
      sha256 "44f26891b158e46a46ea357d1362579d81f034deeab0dd0552ca8458a1e3fc93"

      def install
        bin.install "bomctl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/bomctl/bomctl/releases/download/v0.4.2/bomctl_0.4.2_darwin_arm64.tar.gz"
      sha256 "dbf648b6945b7cb2fab7c4799d23d0a15dfea02c64bab1bd139e3b44ab48b75c"

      def install
        bin.install "bomctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/bomctl/bomctl/releases/download/v0.4.2/bomctl_0.4.2_linux_amd64.tar.gz"
        sha256 "8c7918d08b8703b37986ff0a0944d84962a0c9eabc9a1977cd0efd5c268bda73"

        def install
          bin.install "bomctl"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/bomctl/bomctl/releases/download/v0.4.2/bomctl_0.4.2_linux_arm64.tar.gz"
        sha256 "3849d28576d6c849c04635909140931a7ade2d277c30dc1a8433a5aa3d94ae36"

        def install
          bin.install "bomctl"
        end
      end
    end
  end
end
